'use strict';
const $=id=>document.getElementById(id);
const historical=report=>['sealed_retrospective_market_replay','matched_market_stimulus_assay'].includes(report.source);
let data=null, step=0, bin=0, node=0, edge=0, timer=null, runName='', positions=[], imported=false, viewRequest=0, externalNeuron=false;
const colors={visual:'#8fbcff',KC:'#b2bfd1',DAN:'#e6a8e8',MBON:'#ffbf69',output:'#67e8cf',other:'#b2bfd1'};
const num=(x,d=3)=>Number(x).toLocaleString(undefined,{maximumFractionDigits:d});
const fmt=x=>x===null?'Not defined':typeof x==='number'?num(x):String(x);
function error(e){$('error').textContent=e?.message||String(e);}
async function api(path, options){const r=await fetch(path,options);const body=await r.json();if(!r.ok)throw new Error(body.error||r.statusText);return body;}
function options(el, values){el.replaceChildren(...values.map(([v,label])=>{const o=document.createElement('option');o.value=v;o.textContent=label;return o;}));}
function dl(el,rows){el.replaceChildren();for(const [k,v] of rows){let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=fmt(v);el.append(dt,dd);}}
function chart(id, xs, series, unit, cursor){
 const el=$(id),w=Math.max(250,el.clientWidth),h=175,left=60,right=w-16,top=16,bottom=137;
 const values=series.flatMap(s=>s.values);let ymin=Math.min(...values),ymax=Math.max(...values);if(ymin===ymax){ymin-=1;ymax+=1;}const pad=(ymax-ymin)*.08;ymin-=pad;ymax+=pad;
 const xmin=xs[0],xmax=xs.at(-1),X=x=>left+(x-xmin)/(xmax-xmin||1)*(right-left),Y=y=>bottom-(y-ymin)/(ymax-ymin)*(bottom-top);
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`${unit} over neural time in milliseconds`);
 const add=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};
 add('rect',{x:left,y:top,width:right-left,height:bottom-top,fill:'none',stroke:'#35445c'});
 for(let k=0;k<3;k++){const v=ymin+(ymax-ymin)*k/2;add('text',{x:left-8,y:Y(v)+4,'text-anchor':'end',fill:'#b2bfd1','font-size':11},num(v,2));}
 for(let k=0;k<3;k++){const x=xmin+(xmax-xmin)*k/2;add('text',{x:X(x),y:bottom+17,'text-anchor':k===0?'start':k===2?'end':'middle',fill:'#b2bfd1','font-size':11},num(x));}
 add('text',{x:left,y:12,fill:'#b2bfd1','font-size':11},unit);add('text',{x:(left+right)/2,y:173,'text-anchor':'middle',fill:'#b2bfd1','font-size':11},'Neural time (ms)');
 for(const s of series)add('path',{d:s.values.map((v,i)=>`${i?'L':'M'}${X(xs[i])},${Y(v)}`).join(' '),fill:'none',stroke:s.color,'stroke-width':1.7});
 if(cursor!==undefined)add('line',{x1:X(xs[cursor]),x2:X(xs[cursor]),y1:top,y2:bottom,stroke:'#e8edf6','stroke-dasharray':'3 4'});
 const legend=document.createElement('p');legend.className='small';legend.textContent=series.map(s=>s.name).join(' / ');el.replaceChildren(svg,legend);
}
function restoredEdges(f){return f.event.phase==='probe'?data.report.probe_boundary?.restoration?.edge_ids||[]:data.report.restoration?.edge_ids||[];}
function network(f){
 const svg=$('network'),rect=svg.getBoundingClientRect(),w=rect.width,h=rect.height;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();
 const ns='http://www.w3.org/2000/svg',add=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};
 const groups=['visual','KC','DAN','MBON','output','other'].filter(g=>data.nodes.some(n=>n.group===g));positions=Array(data.nodes.length);
 for(const[gidx,g]of groups.entries()){const members=data.nodes.map((n,i)=>n.group===g?i:-1).filter(i=>i>=0);const x=25+(w-50)*gidx/(groups.length-1||1);add('text',{x,y:16,fill:colors[g],'font-size':11,'text-anchor':gidx===0?'start':gidx===groups.length-1?'end':'middle'},g==='visual'?'Visual':g==='output'?'Decoder':g);members.forEach((i,j)=>positions[i]=[x+(j%2?4:-4),40+(h-60)*(j+.5)/members.length]);}
 const pmap=new Map(data.plastic_selection.map((v,i)=>[v,i]));
 const restored=new Set(restoredEdges(f));
 for(const e of data.edges){const [x,y]=positions[e.source],[tx,ty]=positions[e.target],pi=pmap.get(e.plastic_index),changed=pi!==undefined&&Math.abs(f.plastic_weights[bin][pi]-($('pristine').checked?e.weight:f.plastic_initial[pi]))>1e-9,active=f.counts[bin][e.source]>0;
 add('path',{d:`M${x},${y} Q${(x+tx)/2+12},${(y+ty)/2-8} ${tx},${ty}`,fill:'none',stroke:restored.has(String(e.id))?'#c4a1ff':changed?'#ffbf69':active?'#67e8cf':'#35445c',opacity:restored.has(String(e.id))?.85:changed?.65:active?.3:.2,'stroke-width':restored.has(String(e.id))?1.4:changed?1.1:.6});}
 data.nodes.forEach((n,i)=>{const[x,y]=positions[i],active=f.counts[bin][i]>0;const circle=add('circle',{cx:x,cy:y,r:active?4.5:2.5,fill:active?'#67e8cf':colors[n.group],opacity:active?1:.6});const title=document.createElementNS(ns,'title');title.textContent=`${n.type} ${n.id}: ${f.counts[bin][i]} spikes`;circle.append(title);if(i===node)add('circle',{cx:x,cy:y,r:7,fill:'none',stroke:'#fff','stroke-width':1.5});});
}
function spikeBin(direction){
 if(!data)return -1;
 const counts=data.frames[step].counts;
 for(let i=bin+direction;i>=0&&i<counts.length;i+=direction)if(counts[i][node]>0)return i;
 return -1;
}
function jumpSpike(direction){const target=spikeBin(direction);if(target<0)return;clearInterval(timer);timer=null;$('play').textContent='Play bins';bin=target;draw();}
function momentLink(){
 const link=$('moment-link');link.hidden=imported||externalNeuron||!runName;if(link.hidden)return;
 const url=new URL(location.href);url.search='';url.searchParams.set('run',runName);url.searchParams.set('step',step);url.searchParams.set('bin',bin);url.searchParams.set('neuron',data.nodes[node].id);
 const selectedEdge=data.edges.filter(e=>e.plastic_index!==null)[edge];if(selectedEdge)url.searchParams.set('edge',selectedEdge.id);
 if($('compare').value)url.searchParams.set('compare',$('compare').value);link.href=url.href;
}
function draw(){if(!data)return;externalNeuron=false;document.querySelector('.legend .changed').parentElement.lastChild.textContent=$('pristine').checked?'Plastic edge differs from pristine state':'Plastic edge changed since observation start';const f=data.frames[step],n=data.nodes[node];bin=Math.min(bin,f.times_ms.length-1);$('bin').max=f.times_ms.length-1;$('bin').value=bin;$('time').textContent=num(f.times_ms[bin])+' ms';network(f);
 document.querySelector('.legend .restored').parentElement.lastChild.textContent=data.report.restoration?'Restored before replay':'Restored before probe';
 $('previous-spike').disabled=spikeBin(-1)<0;$('next-spike').disabled=spikeBin(1)<0;momentLink();
 $('neuron-detail').textContent=`${n.type||'Unannotated'} · ${n.id} · ${f.counts[bin][node]} spikes in this bin · ${num(f.voltage[bin][node])} mV`;
 chart('neuron-chart',f.times_ms,[{name:'Selected neuron voltage',values:f.voltage.map(v=>v[node]),color:'#8fbcff'}],'Voltage (mV)',bin);
 $('input').src='data:image/png;base64,'+f.input_png;$('input-info').textContent=`${f.event.phase||'assay'} · ${f.event.input_preset||data.report.config.preset} · ${data.report.config.view} ${f.event.input_amplitude===undefined?"":"· movement ×"+num(f.event.input_amplitude)} · ${f.event.input_news||data.report.config.news} news`;$('encoding-note').textContent=data.report.config.view==='fixed_returns'?'Fixed return scale, referenced to the first price in the window. Bounds: 0.01×–100× that price; amber points mark clipping. See provenance for the exact transform.':'';
 $('phase-note').textContent=f.event.phase==='probe'?`Frozen probe: neural activity was reset; ${data.report.probe_boundary.restoration?.mode&&data.report.probe_boundary.restoration.mode!=='none'?`${num(data.report.probe_boundary.restoration.edge_count)} connections restored to pristine memory (${data.report.probe_boundary.restoration.mode})`:'trained weights were retained'}. Weight L2 from pristine: ${num(data.report.probe_boundary.weight_delta_from_pristine_l2,6)}. No reinforcement or extra current.`:data.report.source==='matched_market_stimulus_assay'?`Historical replay: ${data.report.config.memory} memory; ${data.report.config.learning?'updates enabled':'weights and memory frozen'}; pulses ${data.report.config.pulses}.${data.report.restoration?.post_ids?.length?` Restored ${num(data.report.restoration.edge_count)} incoming connections to body IDs ${data.report.restoration.post_ids.join(', ')} before replay.`:''} No fills or returns recomputed.`:data.report.restoration?.post_ids?.length?`Market replay: ${num(data.report.restoration.edge_count)} incoming connections to body IDs ${data.report.restoration.post_ids.join(', ')} restored to pristine before inference. Training memory is retained elsewhere; inference is frozen.`:'';$('decision').textContent=f.event.side;dl($('decoder'),[['Left DNp20 (Hz)',f.event.left_hz],['Right DNp20 (Hz)',f.event.right_hz],['Right − left (Hz)',f.event.difference_hz],['Gate spikes',f.event.gate_spikes],['Reinforcement',f.event.stimulus]]);
 dl($('metrics'),[['Plasticity enabled',f.event.diagnostics.plasticity_enabled??data.report.config.learning],[$('pristine').checked?'Changed edges vs pristine':'Changed edges at cursor',($('pristine').checked?f.changed_from_pristine:f.changed_edges)[bin]],[$('pristine').checked?'Weight Δ L2 vs pristine':'Weight Δ L2 at cursor',($('pristine').checked?f.weight_from_pristine_l2:f.weight_delta_l2)[bin]],['Memory u L2',f.memory_u_l2[bin]],['Memory w L2',f.memory_w_l2[bin]],['Loss',null],['Backprop gradient',null],['Clipped edges (end)',f.event.diagnostics.clipped_edges]]);
 chart('spike-chart',f.times_ms,[{name:'All retained neurons',values:f.total_spikes,color:'#67e8cf'}],'Spikes / 10 ms',bin);
 chart('weight-chart',f.times_ms,[{name:$('pristine').checked?'All plastic edges: L2 from pristine':'All plastic edges: L2 from observation start',values:$('pristine').checked?f.weight_from_pristine_l2:f.weight_delta_l2,color:'#ffbf69'}],'Weight Δ L2',bin);
 chart('trace-chart',f.times_ms,[{name:'KC trace',values:f.kc_mean_hz,color:'#8fbcff'},{name:'DAN trace',values:f.dan_mean_hz,color:'#e6a8e8'}],'Mean trace (Hz)',bin);
 const plastic=data.edges.filter(e=>e.plastic_index!==null),e=plastic[edge];if(e){const pi=data.plastic_selection.indexOf(e.plastic_index);$('edge-detail').textContent=`Edge ${e.id} · ${data.nodes[e.source].id} → ${data.nodes[e.target].id} · weight ${num(f.plastic_weights[bin][pi],6)} · Δ ${num(f.plastic_weights[bin][pi]-($('pristine').checked?e.weight:f.plastic_initial[pi]),6)} · source spikes ${f.counts[bin][e.source]}${restoredEdges(f).includes(String(e.id))?` · restored to pristine memory before ${f.event.phase==='probe'?'probe':'replay'}`:''}`;chart('edge-chart',f.times_ms,[{name:'Synaptic weight',values:f.plastic_weights.map(v=>v[pi]),color:'#ffbf69'}],'Weight (model units)',bin);}
}
function table(headers, rows){const t=document.createElement('table'),head=document.createElement('tr');for(const title of headers){const th=document.createElement('th');th.textContent=title;head.append(th);}t.append(head);for(const values of rows){const row=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=value;row.append(td);}t.append(row);}return t;}
function utc(ts){return new Date(ts*1000).toISOString().slice(11,19);}
function marketTimeline(report){
 const rows=report.market_timeline;$('market-panel').hidden=report.source!=='sealed_retrospective_market_replay';$('market-timeline').replaceChildren();
 if(!rows){$('market-coverage').textContent='This older recording has no decision timeline. Consult its study ledger for skipped observations and fills.';return;}
 const decisions=rows.filter(r=>!r.terminal),observed=decisions.filter(r=>r.observation==='observed').length,fills=rows.filter(r=>r.fill_status==='filled').length;
 $('market-coverage').textContent=`${observed} / ${decisions.length} decision slots observed · ${fills} simulated fills · ${decisions.length-observed} skipped. Times are UTC.`;
 $('market-timeline').append(table(['Decision UTC','Quote UTC','Observation','Output','Fill from prior decision','Sleeve equity'],rows.map(r=>[utc(r.decision_ts),utc(r.quote_ts),r.observation.replaceAll('_',' '),r.action??'—',r.fill_reason?`${r.fill_status}: ${r.fill_reason}`:r.fill_status,'$'+Number(r.equity).toFixed(2)])));
}
function load(d){if(!d.report||!d.nodes?.length||!d.frames?.length)throw new Error('Not a fly view.json recording');data=d;$('pristine').checked=false;$('pristine').disabled=!d.frames.every(f=>f.weight_from_pristine_l2&&f.changed_from_pristine);marketTimeline(d.report);const market=d.report.source==='sealed_retrospective_market_replay',mechanics=d.report.source==='matched_market_stimulus_assay';$('source-badge').textContent=mechanics?'Historical inputs · neural diagnostic':market?'Market replay · simulated fills':'Synthetic assay · paper only';$('decoder-note').textContent=mechanics?'Recorded market images with controlled memory, updates, and stimulation. This is a neural diagnostic; no account, fills, or returns are recomputed.':market?'Whole-observation result (500 ms). Simulated fills are recorded in the study ledger. This viewer sends no orders.':'Whole-observation result (500 ms). BUY/SELL are engineered mappings of downstream firing rates; this assay executes no trades.';step=bin=node=edge=0;clearInterval(timer);timer=null;$('play').textContent='Play bins';options($('step'),d.frames.map((f,i)=>[i,`${f.event.phase?f.event.phase+' '+f.event.phase_step:i+1} · ${f.event.side}`]));options($('node'),d.nodes.map((n,i)=>[i,`${n.group}: ${n.type||n.id} · ${n.id}`]));options($('edge'),d.edges.filter(e=>e.plastic_index!==null).map((e,i)=>[i,`${e.id} · ${d.nodes[e.source].type} → ${d.nodes[e.target].type}`]));$('graph-size').textContent=`${num(d.report.graph.neurons)} neurons / ${num(d.report.graph.edges)} connections simulated`;$('selection').textContent=`Showing ${d.nodes.length} neurons and ${d.edges.length} connections. ${d.selection}`;$('provenance').textContent=JSON.stringify(d.report,null,2);$('status').textContent=`Loaded ${runName||'imported trace'} · ${d.frames.length} observations · ${num(d.report.seconds,1)} s capture time`;$('comparison').replaceChildren();$('compare').value='';draw();}
async function loadRun(name){const ticket=++viewRequest;$('error').textContent='';const recording=await api('/api/view?run='+encodeURIComponent(name));if(ticket!==viewRequest)return;runName=name;$('runs').value=name;imported=false;load(recording);}
async function refresh(){const r=await api('/api/runs');const prior=$('runs').value;options($('runs'),r.runs.map(n=>[n,n]));options($('compare'),[['','Choose a run'],...r.runs.map(n=>[n,n])]);$('run').disabled=!r.can_run;$('run').textContent=!r.can_run?'Read-only recordings':r.backend==='modal'?'Run on Modal (cloud)':'Run full-network assay';if(r.runs.includes(prior))$('runs').value=prior;if(!data&&r.runs.length){const requested=new URLSearchParams(location.search).get('run');await loadRun(r.runs.includes(requested)?requested:r.runs.at(-1));}if(!r.runs.length&&!data)$('status').textContent='No recordings yet. Run an assay or import a view.json.';}
async function status(initial=false){const s=await api('/api/status');if(!s.run||(initial&&['succeeded','not_started'].includes(s.status)))return;const log=await api('/api/log?run='+encodeURIComponent(s.run));$('log').textContent=log.log;$('status').textContent=`${s.run}: ${s.status}`;if(s.status==='running'){setTimeout(()=>status().catch(error),2000);}else{$('run').disabled=false;if(s.status==='succeeded'){await refresh();$('runs').value=s.run;await loadRun(s.run);}else error(s.error||('Assay '+s.status+'. See worker log or Modal call.'));}}
$('assay').onsubmit=async e=>{e.preventDefault();$('error').textContent='';const f=new FormData(e.target);const config=Object.fromEntries(f);config.steps=Number(f.get('steps'));config.probe_steps=Number(f.get('probe_steps'));config.amplitude=Number(f.get('amplitude'));config.probe_amplitude=Number(f.get('probe_amplitude'));config.eta=Number(f.get('eta'));config.current=Number(f.get('current'));config.learning=f.has('learning');config.reinforcement_only=f.has('reinforcement_only');config.probe_edges=String(f.get('probe_edges')).split(',').map(x=>x.trim()).filter(Boolean);config.neurons=String(f.get('neurons')).split(',').map(x=>x.trim()).filter(Boolean);try{$('run').disabled=true;await api('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});await status();}catch(e){$('run').disabled=false;error(e);}};
$('runs').onchange=e=>loadRun(e.target.value).catch(error);$('refresh').onclick=()=>refresh().catch(error);$('step').onchange=e=>{step=Number(e.target.value);bin=0;draw();};$('bin').oninput=e=>{bin=Number(e.target.value);draw();};$('node').onchange=e=>{node=Number(e.target.value);draw();};$('edge').onchange=e=>{edge=Number(e.target.value);draw();};
$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='Play bins';return;}if(!data)return;$('play').textContent='Pause';timer=setInterval(()=>{bin++;if(bin>=data.frames[step].times_ms.length){bin=0;step=(step+1)%data.frames.length;$('step').value=step;}draw();},150);};
$('pristine').onchange=()=>draw();
$('previous-spike').onclick=()=>jumpSpike(-1);$('next-spike').onclick=()=>jumpSpike(1);
$('network').onclick=e=>{const r=$('network').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=22;positions.forEach(([nx,ny],i)=>{const d=Math.hypot(x-nx,y-ny);if(d<best){best=d;node=i;}});$('node').value=node;draw();};
$('lookup-button').onclick=async()=>{try{if(imported)throw new Error('Full-neuron lookup needs the recording server and its NPZ files.');const id=$('lookup').value.trim(),d=await api('/api/neuron?run='+encodeURIComponent(runName)+'&id='+encodeURIComponent(id)),f=d.frames[step];$('neuron-detail').textContent=`Full recording: ${d.id} · ${num(f.counts.reduce((a,b)=>a+b,0))} spikes in observation · ${f.plastic_edges.length} adjacent plastic edges`;chart('neuron-chart',f.times_ms,[{name:'Queried neuron voltage',values:f.voltage,color:'#8fbcff'}],'Voltage (mV)',bin);$('lookup-button').title=JSON.stringify(f.plastic_edges);externalNeuron=true;$('previous-spike').disabled=$('next-spike').disabled=true;momentLink();}catch(e){error(e);}};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>15000000)throw new Error('Trace JSON must be under 15 MB');runName=file.name;imported=true;load(JSON.parse(await file.text()));}catch(e){error(e);}};
$('compare').onchange=async e=>{try{
 if(!data)return;momentLink();if(!e.target.value){++viewRequest;$('comparison').replaceChildren();return;}
 const current=data,currentName=runName,otherName=e.target.value,request=++viewRequest,other=await api('/api/view?run='+encodeURIComponent(otherName));
 if(request!==viewRequest||current!==data)return;
 const market=historical(current.report),otherMarket=historical(other.report);
 if(market!==otherMarket){$('comparison').textContent='A synthetic assay and a market replay cannot be paired by observation index.';return;}
 const byTime=new Map(other.frames.map(f=>[f.event.market_decision_ts,f]));const phaseKey=(f,i)=>`${f.event.phase||'assay'}:${f.event.phase_step||i+1}`;const byPhase=new Map(other.frames.map((f,i)=>[phaseKey(f,i),f]));
 const matched=current.frames.map((f,i)=>[f,market?byTime.get(f.event.market_decision_ts):byPhase.get(phaseKey(f,i)),i]).filter(([f,o])=>o&&(!market||Number.isFinite(f.event.market_decision_ts)));
 const wrap=document.createElement('div');wrap.className='table-wrap';
 wrap.append(table([market?'Decision UTC':'Phase / observation','Current action','Other action','Current R−L Hz','Other R−L Hz','Current gate spikes','Other gate spikes','Input identical'],matched.map(([f,o,i])=>[market?utc(f.event.market_decision_ts):phaseKey(f,i),f.event.side,o.event.side,num(f.event.difference_hz),num(o.event.difference_hz),f.event.gate_spikes,o.event.gate_spikes,f.event.input_sha256===o.event.input_sha256?'Yes':'No'])));
 const names=document.createElement('p');names.textContent=`Current: ${currentName} · Other: ${otherName}`;const note=document.createElement('p');note.textContent=market?`${matched.length} shared decision timestamps. Unmatched slots are excluded; inspect each timeline for gaps.`:`${matched.length} observations paired by phase and within-phase index.`;
 if([current,other].some(d=>d.report.source==='matched_market_stimulus_assay'))note.textContent+=' Neural responses only: the diagnostic does not recompute fills or returns.';
 const currentBuild=current.report.native_build?.binary_sha256,otherBuild=other.report.native_build?.binary_sha256;if(!currentBuild||!otherBuild)note.textContent+=' Native build provenance is missing; controlled pairing is unverified.';else if(currentBuild!==otherBuild)note.textContent+=' Native binaries differ; this comparison includes build/platform effects.';const config=document.createElement('pre');config.textContent=JSON.stringify({current:current.report.config,comparison:other.report.config},null,2);const details=document.createElement('details'),heading=document.createElement('summary');heading.textContent='Compared configurations';details.append(heading,config);$('comparison').replaceChildren(names,note,wrap,details);
 }catch(e){error(e);}};
window.addEventListener('resize',()=>draw());refresh().then(async()=>{
 const q=new URLSearchParams(location.search);
 const index=(name,length)=>{const value=q.get(name);if(!value||!/^\d+$/.test(value))return -1;const n=Number(value);return Number.isSafeInteger(n)&&n<length?n:-1;};
 if(data){
  const selected=index('step',data.frames.length);if(selected>=0){step=selected;$('step').value=step;}
  const selectedBin=index('bin',data.frames[step].times_ms.length);if(selectedBin>=0)bin=selectedBin;
  const selectedNode=data.nodes.findIndex(n=>String(n.id)===q.get('neuron'));if(selectedNode>=0){node=selectedNode;$('node').value=node;}
  const selectedEdge=data.edges.filter(e=>e.plastic_index!==null).findIndex(e=>String(e.id)===q.get('edge'));if(selectedEdge>=0){edge=selectedEdge;$('edge').value=edge;}
  draw();
 }
 const comparison=q.get('compare');if(comparison&&[...$('compare').options].some(o=>o.value===comparison)){$('compare').value=comparison;await $('compare').onchange({target:$('compare')});}await status(true);}).catch(error);

$('restore-edge').onclick=()=>{if(!data)return;const e=data.edges.filter(e=>e.plastic_index!==null)[edge];if(!e)return;const form=$('assay').elements,ids=form.probe_edges.value.split(',').map(s=>s.trim()).filter(Boolean);if(!ids.includes(String(e.id)))ids.push(String(e.id));if(ids.length>64){error('At most 64 restoration edges');return;}form.probe_edges.value=ids.join(', ');form.probe_restore.value='selected';if(Number(form.probe_steps.value)===0)form.probe_steps.value='1';form.probe_restore.closest('details').open=true;form.probe_restore.focus();};
